version: '3'

services:
  next-app:
    container_name: blanq-docker
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 80:80
    networks:
      - my_network

networks:
  my_network:
    external: true
